In [81]:
import pandas as pd 
import numpy as np 
import seaborn as sns 

from sklearn.utils import resample

In [70]:
Data = sns.load_dataset('titanic')

In [71]:
Data.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [72]:
Data['age']=Data ['age'].fillna(Data['age'].median())

In [73]:
Q1,Q3 = np.quantile(Data['age'],[0.25,0.75])
IQR = Q3 -Q1


median_age = Data['age'].median()


High_fence = Q3 +1.5*(IQR)
Data['age'].max()
Data.loc[Data['age']>High_fence,'age'] = median_age

In [74]:
Data['age'].max()

np.float64(54.0)

In [75]:
Data['embarked']=Data['embarked'].fillna(Data['embarked'].mode()[0])
Data['deck']=Data['deck'].fillna(Data['deck'].mode()[0])
Data['embark_town']=Data['embark_town'].fillna(Data['embark_town'].mode()[0])

In [76]:
Data.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [78]:
Data['sex'].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [83]:
# Upsampling Minority Class
majority = Data[Data['sex']=="male"]
minority = Data[Data['sex'] =="female"]

In [84]:
Upsampled_Data = resample (
    minority,
    replace=True,
    n_samples=len(majority),
    random_state=50

)

In [86]:
Final_data = pd.concat([majority,Upsampled_Data])

In [88]:
Final_data['sex'].value_counts()

sex
male      577
female    577
Name: count, dtype: int64

In [89]:
Final_data.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [90]:
Final_data

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,C,Southampton,no,True
5,0,3,male,28.0,0,0,8.4583,Q,Third,man,True,C,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,C,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41,0,2,female,27.0,1,0,21.0000,S,Second,woman,False,C,Southampton,no,False
483,1,3,female,28.0,0,0,9.5875,S,Third,woman,False,C,Southampton,yes,True
446,1,2,female,13.0,0,1,19.5000,S,Second,child,False,C,Southampton,yes,False
409,0,3,female,28.0,3,1,25.4667,S,Third,woman,False,C,Southampton,no,False
307,1,1,female,17.0,1,0,108.9000,C,First,woman,False,C,Cherbourg,yes,False

In [92]:
Final_data['class'].value_counts()
First = Final_data[Final_data['class'] == 'First']
Second = Final_data[Final_data['class'] == 'Second']
Third = Final_data[Final_data['class'] == 'Third']

In [96]:
# DownSampling the Data 
DownSampled_Class_First = resample(
    First,
    replace=True,
    n_samples= 200 ,
    random_state=52,
)

DownSampled_Class_Second = resample(
    Second,
    replace=True,
    n_samples= 200 ,
    random_state=52,
)

DownSampled_Class_Third = resample(
    Third,
    replace=True,
    n_samples= 200 ,
    random_state=52,
)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
649,1,3,female,23.00,0,0,7.5500,S,Third,woman,False,C,Southampton,yes,True
406,0,3,male,51.00,0,0,7.7500,S,Third,man,True,C,Southampton,no,True
207,1,3,male,26.00,0,0,18.7875,C,Third,man,True,C,Cherbourg,yes,True
216,1,3,female,27.00,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True
620,0,3,male,27.00,1,0,14.4542,C,Third,man,True,C,Cherbourg,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409,0,3,female,28.00,3,1,25.4667,S,Third,woman,False,C,Southampton,no,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,C,Cherbourg,yes,False
114,0,3,female,17.00,0,0,14.4583,C,Third,woman,False,C,Cherbourg,no,True
79,1,3,female,30.00,0,0,12.4750,S,Third,woman,False,C,Southampton,yes,True
160,0,3,male,44.00,0,1,16.1000,S,Third,man,True,C,Southampton,no,False

In [99]:
Final_data = pd.concat([DownSampled_Class_Third,DownSampled_Class_First,DownSampled_Class_Second]).reset_index(drop=True)

In [103]:
Final_data

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,1,3,female,23.0,0,0,7.5500,S,Third,woman,False,C,Southampton,yes,True
1,0,3,male,51.0,0,0,7.7500,S,Third,man,True,C,Southampton,no,True
2,1,3,male,26.0,0,0,18.7875,C,Third,man,True,C,Cherbourg,yes,True
3,1,3,female,27.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True
4,0,3,male,27.0,1,0,14.4542,C,Third,man,True,C,Cherbourg,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,1,2,female,13.0,0,1,19.5000,S,Second,child,False,C,Southampton,yes,False
596,1,2,female,29.0,1,0,26.0000,S,Second,woman,False,C,Southampton,yes,False
597,1,2,female,29.0,1,0,26.0000,S,Second,woman,False,C,Southampton,yes,False
598,0,2,male,34.0,1,0,21.0000,S,Second,man,True,C,Southampton,no,False
599,1,2,female,4.0,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False

In [119]:
Final_data.drop('adult_male',axis=1,inplace=True)

In [107]:
Final_data['alive'].value_counts()

alive
yes    308
no     292
Name: count, dtype: int64

In [108]:
Final_data['who'].value_counts()

who
woman    275
man      275
child     50
Name: count, dtype: int64

In [113]:
Final_data.drop('sibsp',axis=1,inplace=True)

In [112]:
Final_data.drop('parch',axis=True,inplace=True)

In [115]:
Final_data.drop('who',axis=1,inplace=True)

In [117]:
Final_data.drop('class',axis=1,inplace=True)

In [121]:
Final_data.to_csv("Cleaned_Data.csv")