In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.utils import resample

In [3]:
Data=sns.load_dataset("diamonds")
Data

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [4]:
Data.isnull().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [5]:
Data['color'].value_counts()
Data['cut'].value_counts()

cut
Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: count, dtype: int64

In [6]:
Data['Cut_Color'] = Data['cut'].astype(str)+"_"+Data['color'].astype(str)

In [15]:
Data.drop_duplicates(inplace=True)
Data.info()
Data.describe()

<class 'pandas.DataFrame'>
Index: 53794 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   carat      53794 non-null  float64
 1   cut        53794 non-null  category
 2   color      53794 non-null  category
 3   clarity    53794 non-null  category
 4   depth      53794 non-null  float64
 5   table      53794 non-null  float64
 6   price      53794 non-null  int64
 7   x          53794 non-null  float64
 8   y          53794 non-null  float64
 9   z          53794 non-null  float64
 10  Cut_Color  53794 non-null  str
dtypes: category(3), float64(6), int64(1), str(1)
memory usage: 3.8 MB

,carat,depth,table,price,x,y,z
count,53794.00000,53794.000000,53794.000000,53794.000000,53794.000000,53794.000000,53794.000000
mean,0.79778,61.748080,57.458109,3933.065082,5.731214,5.734653,3.538714
std,0.47339,1.429909,2.233679,3988.114460,1.120695,1.141209,0.705037
min,0.20000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.40000,61.000000,56.000000,951.000000,4.710000,4.720000,2.910000
50%,0.70000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.04000,62.500000,59.000000,5326.750000,6.540000,6.540000,4.030000
max,5.01000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [9]:
Data.duplicated().sum()

np.int64(0)

In [16]:
Data.to_csv("Cleaaned_Data.csv")
Data

,carat,cut,color,clarity,depth,table,price,x,y,z,Cut_Color
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,Ideal_E
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,Premium_E
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,Good_E
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,Premium_I
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,Good_J
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,Ideal_D
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,Good_D
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,Very Good_D
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,Premium_H
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,Ideal_D

In [20]:
Data.drop("cut",axis=1,inplace=True)
Data.drop("color",axis=1,inplace=True)

In [28]:
Numeric_data= Data.select_dtypes(include=['number'])
Correlation_Coef = Numeric_data.corr()
Correlation_Coef

          carat     depth     table     price         x         y         z
carat  1.000000  0.027861  0.181091  0.921548  0.975380  0.951908  0.953542
depth  0.027861  1.000000 -0.297669 -0.011048 -0.025348 -0.029389  0.094757
table  0.181091 -0.297669  1.000000  0.126566  0.194855  0.183231  0.150270
price  0.921548 -0.011048  0.126566  1.000000  0.884504  0.865395  0.861208
x      0.975380 -0.025348  0.194855  0.884504  1.000000  0.974592  0.970686
y      0.951908 -0.029389  0.183231  0.865395  0.974592  1.000000  0.951844
z      0.953542  0.094757  0.150270  0.861208  0.970686  0.951844  1.000000

In [31]:
Data['Cut_Color'].value_counts()

Cut_Color
Ideal_G        4865
Ideal_E        3893
Ideal_F        3819
Ideal_H        3104
Premium_G      2918
Ideal_D        2823
Very Good_E    2399
Premium_H      2351
Premium_E      2331
Premium_F      2321
Very Good_G    2298
Very Good_F    2163
Ideal_I        2090
Very Good_H    1819
Premium_D      1599
Very Good_D    1510
Premium_I      1422
Very Good_I    1203
Good_E          931
Good_F          908
Ideal_J         894
Good_G          869
Premium_J       806
Good_H          699
Very Good_J     677
Good_D          660
Good_I          518
Fair_G          312
Fair_F          309
Good_J          306
Fair_H          299
Fair_E          222
Fair_I          174
Fair_D          163
Fair_J          119
Name: count, dtype: int64

# Balancing the Cut Color Column

In [70]:
import pandas as pd
from sklearn.utils import resample

# Target number of samples for EVERY class
target_n = 2500

# Container to hold our newly balanced subsets
balanced_subsets = []

# Get a list of all unique combinations in Cut_Color
unique_classes = Data['Cut_Color'].unique()

for current_class in unique_classes:
    # 1. Isolate the rows belonging to the current class
    class_data = Data[Data['Cut_Color'] == current_class]
    current_count = len(class_data)
    
    # 2. Determine if we need to upsample (with replacement) or downsample (without replacement)
    if current_count < target_n:
        # Upsampling minority classes (e.g., Fair_J, Good_E, etc.)
        resampled_subset = resample(
            class_data,
            replace=True,      # Mandatory for upsampling
            n_samples=target_n,
            random_state=50
        )
    else:
        # Downsampling majority classes (e.g., Ideal_G, Ideal_E, etc.)
        resampled_subset = resample(
            class_data,
            replace=False,     # Best practice for downsampling to keep rows unique
            n_samples=target_n,
            random_state=50
        )
        
    # Append the balanced subset to our list
    balanced_subsets.append(resampled_subset)

# 3. Combine all balanced subsets back into a single dataframe
Balanced_Data = pd.concat(balanced_subsets).reset_index(drop=True)

# 4. Verify the results
print("--- New Value Counts ---")
print(Balanced_Data['Cut_Color'].value_counts())

--- New Value Counts ---
Cut_Color
Ideal_E        2500
Premium_E      2500
Good_E         2500
Premium_I      2500
Good_J         2500
Very Good_J    2500
Very Good_I    2500
Very Good_H    2500
Fair_E         2500
Ideal_J        2500
Premium_F      2500
Ideal_I        2500
Good_I         2500
Very Good_E    2500
Very Good_G    2500
Very Good_D    2500
Very Good_F    2500
Good_F         2500
Good_H         2500
Good_D         2500
Ideal_G        2500
Premium_D      2500
Premium_J      2500
Ideal_D        2500
Premium_G      2500
Premium_H      2500
Fair_F         2500
Ideal_F        2500
Fair_H         2500
Ideal_H        2500
Good_G         2500
Fair_G         2500
Fair_J         2500
Fair_I         2500
Fair_D         2500
Name: count, dtype: int64

In [72]:
Balanced_Data.to_csv('Cleaned_Data.csv')

# Data Encoding 
We will be using the Target Encoding Bacause we Have the Target Column Price

In [63]:
Mean_Price = Balanced_Data.groupby('clarity')['price'].mean()
Balanced_Data['clarity_Encoded'] = Balanced_Data['clarity'].map(Mean_Price)

In [64]:
Balanced_Data

,carat,clarity,depth,table,price,x,y,z,Cut_Color,clarity_Encoded
0,0.55,VS1,61.7,55.0,1975,5.27,5.29,3.26,Ideal_E,4063.283964
1,0.58,VS2,61.9,56.0,1670,5.34,5.38,3.32,Ideal_E,4255.457325
2,0.56,VVS2,62.6,54.0,2463,5.32,5.28,3.32,Ideal_E,3304.891671
3,0.34,VS1,62.2,55.0,805,4.49,4.52,2.80,Ideal_E,4063.283964
4,0.35,VS1,61.6,55.1,771,4.54,4.58,2.81,Ideal_E,4063.283964
...,...,...,...,...,...,...,...,...,...,...
87495,1.00,SI1,65.5,60.0,5331,6.18,6.12,4.03,Fair_D,4174.335950
87496,1.01,VS2,59.1,68.0,5797,6.56,6.44,3.84,Fair_D,4255.457325
87497,0.90,SI2,64.9,57.0,3473,6.03,5.98,3.90,Fair_D,5227.413731
87498,1.50,SI2,68.8,57.0,7469,6.90,6.86,4.73,Fair_D,5227.413731
87499,1.50,I1,64.7,62.0,5460,7.19,7.04,4.60,Fair_D,4072.084746

In [67]:
Balanced_Data.drop("clarity",axis=1,inplace=True)

In [68]:
Encoded_Data = Balanced_Data

In [69]:
Encoded_Data

       carat  depth  table  price     x     y     z Cut_Color clarity_Encoded
0       0.55   61.7   55.0   1975  5.27  5.29  3.26   Ideal_E     4063.283964
1       0.58   61.9   56.0   1670  5.34  5.38  3.32   Ideal_E     4255.457325
2       0.56   62.6   54.0   2463  5.32  5.28  3.32   Ideal_E     3304.891671
3       0.34   62.2   55.0    805  4.49  4.52  2.80   Ideal_E     4063.283964
4       0.35   61.6   55.1    771  4.54  4.58  2.81   Ideal_E     4063.283964
...      ...    ...    ...    ...   ...   ...   ...       ...             ...
87495   1.00   65.5   60.0   5331  6.18  6.12  4.03    Fair_D     4174.335950
87496   1.01   59.1   68.0   5797  6.56  6.44  3.84    Fair_D     4255.457325
87497   0.90   64.9   57.0   3473  6.03  5.98  3.90    Fair_D     5227.413731
87498   1.50   68.8   57.0   7469  6.90  6.86  4.73    Fair_D     5227.413731
87499   1.50   64.7   62.0   5460  7.19  7.04  4.60    Fair_D     4072.084746

[87500 rows x 9 columns]

In [75]:
Mean_Price_Cut_Color = Encoded_Data.groupby('Cut_Color')['price'].mean()
Encoded_Data['Cut_Color_Encoded'] = Encoded_Data['Cut_Color'].map(Mean_Price_Cut_Color)
Encoded_Data.drop("Cut_Color",axis=1,inplace=True)

In [77]:
Encoded_Data

,carat,depth,table,price,x,y,z,clarity_Encoded,Cut_Color_Encoded
0,0.55,61.7,55.0,1975,5.27,5.29,3.26,4063.283964,2538.9192
1,0.58,61.9,56.0,1670,5.34,5.38,3.32,4255.457325,2538.9192
2,0.56,62.6,54.0,2463,5.32,5.28,3.32,3304.891671,2538.9192
3,0.34,62.2,55.0,805,4.49,4.52,2.80,4063.283964,2538.9192
4,0.35,61.6,55.1,771,4.54,4.58,2.81,4063.283964,2538.9192
...,...,...,...,...,...,...,...,...,...
87495,1.00,65.5,60.0,5331,6.18,6.12,4.03,4174.335950,4397.4116
87496,1.01,59.1,68.0,5797,6.56,6.44,3.84,4255.457325,4397.4116
87497,0.90,64.9,57.0,3473,6.03,5.98,3.90,5227.413731,4397.4116
87498,1.50,68.8,57.0,7469,6.90,6.86,4.73,5227.413731,4397.4116
87499,1.50,64.7,62.0,5460,7.19,7.04,4.60,4072.084746,4397.4116

In [78]:
Encoded_Data.to_csv("Encoded_Data.csv")