In [21]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.utils import resample

In [22]:
Data = pd.read_csv("winequality-white.csv",sep=';')
Data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [23]:
Data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 459.3 KB

In [24]:
Data.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000
mean,6.854788,0.278241,0.334192,6.391415,0.045772,35.308085,138.360657,0.994027,3.188267,0.489847,10.514267,5.877909
std,0.843868,0.100795,0.121020,5.072058,0.021848,17.007137,42.498065,0.002991,0.151001,0.114126,1.230621,0.885639
min,3.800000,0.080000,0.000000,0.600000,0.009000,2.000000,9.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.300000,0.210000,0.270000,1.700000,0.036000,23.000000,108.000000,0.991723,3.090000,0.410000,9.500000,5.000000
50%,6.800000,0.260000,0.320000,5.200000,0.043000,34.000000,134.000000,0.993740,3.180000,0.470000,10.400000,6.000000
75%,7.300000,0.320000,0.390000,9.900000,0.050000,46.000000,167.000000,0.996100,3.280000,0.550000,11.400000,6.000000
max,14.200000,1.100000,1.660000,65.800000,0.346000,289.000000,440.000000,1.038980,3.820000,1.080000,14.200000,9.000000

In [25]:
Data.corr()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
fixed acidity,1.000000,-0.022697,0.289181,0.089021,0.023086,-0.049396,0.091070,0.265331,-0.425858,-0.017143,-0.120881,-0.113663
volatile acidity,-0.022697,1.000000,-0.149472,0.064286,0.070512,-0.097012,0.089261,0.027114,-0.031915,-0.035728,0.067718,-0.194723
citric acid,0.289181,-0.149472,1.000000,0.094212,0.114364,0.094077,0.121131,0.149503,-0.163748,0.062331,-0.075729,-0.009209
residual sugar,0.089021,0.064286,0.094212,1.000000,0.088685,0.299098,0.401439,0.838966,-0.194133,-0.026664,-0.450631,-0.097577
chlorides,0.023086,0.070512,0.114364,0.088685,1.000000,0.101392,0.198910,0.257211,-0.090439,0.016763,-0.360189,-0.209934
free sulfur dioxide,-0.049396,-0.097012,0.094077,0.299098,0.101392,1.000000,0.615501,0.294210,-0.000618,0.059217,-0.250104,0.008158
total sulfur dioxide,0.091070,0.089261,0.121131,0.401439,0.198910,0.615501,1.000000,0.529881,0.002321,0.134562,-0.448892,-0.174737
density,0.265331,0.027114,0.149503,0.838966,0.257211,0.294210,0.529881,1.000000,-0.093591,0.074493,-0.780138,-0.307123
pH,-0.425858,-0.031915,-0.163748,-0.194133,-0.090439,-0.000618,0.002321,-0.093591,1.000000,0.155951,0.121432,0.099427
sulphates,-0.017143,-0.035728,0.062331,-0.026664,0.016763,0.059217,0.134562,0.074493,0.155951,1.000000,-0.017433,0.053678
alcohol,-0.120881,0.067718,-0.075729,-0.450631,-0.360189,-0.250104,-0.448892,-0.780138,0.121432,-0.017433,1.000000,0.435575
quality,-0.113663,-0.194723,-0.009209,-0.097577,-0.209934,0.008158,-0.174737,-0.307123,0.099427,0.053678,0.435575,1.000000

In [26]:
Data.drop("residual sugar",axis=1,inplace=True)
Data.drop("citric acid",axis=1,inplace=True)
Data.drop("free sulfur dioxide",axis=1,inplace=True)
Data.drop("pH",axis=1,inplace=True)
# Data.drop(""axis=1,inplace=True)

In [27]:
Data

,fixed acidity,volatile acidity,chlorides,total sulfur dioxide,density,sulphates,alcohol,quality
0,7.0,0.27,0.045,170.0,1.00100,0.45,8.8,6
1,6.3,0.30,0.049,132.0,0.99400,0.49,9.5,6
2,8.1,0.28,0.050,97.0,0.99510,0.44,10.1,6
3,7.2,0.23,0.058,186.0,0.99560,0.40,9.9,6
4,7.2,0.23,0.058,186.0,0.99560,0.40,9.9,6
...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.039,92.0,0.99114,0.50,11.2,6
4894,6.6,0.32,0.047,168.0,0.99490,0.46,9.6,5
4895,6.5,0.24,0.041,111.0,0.99254,0.46,9.4,6
4896,5.5,0.29,0.022,110.0,0.98869,0.38,12.8,7
4897,6.0,0.21,0.020,98.0,0.98941,0.32,11.8,6

In [28]:
# Agregating the Columns
# Average Volatile Acidity 
Average = Data.groupby('quality')['volatile acidity'].mean()
Data['Avg_volatile_acidity'] = Data['quality'].map(Average)
Data.drop("volatile acidity",axis=1,inplace=True)

In [29]:
Data

,fixed acidity,chlorides,total sulfur dioxide,density,sulphates,alcohol,quality,Avg_volatile_acidity
0,7.0,0.045,170.0,1.00100,0.45,8.8,6,0.260564
1,6.3,0.049,132.0,0.99400,0.49,9.5,6,0.260564
2,8.1,0.050,97.0,0.99510,0.44,10.1,6,0.260564
3,7.2,0.058,186.0,0.99560,0.40,9.9,6,0.260564
4,7.2,0.058,186.0,0.99560,0.40,9.9,6,0.260564
...,...,...,...,...,...,...,...,...
4893,6.2,0.039,92.0,0.99114,0.50,11.2,6,0.260564
4894,6.6,0.047,168.0,0.99490,0.46,9.6,5,0.302011
4895,6.5,0.041,111.0,0.99254,0.46,9.4,6,0.260564
4896,5.5,0.022,110.0,0.98869,0.38,12.8,7,0.262767
4897,6.0,0.020,98.0,0.98941,0.32,11.8,6,0.260564

In [30]:
# Average Sulphates 
Avg = Data.groupby ('quality')['sulphates'].mean()
Data['avg_Silphates'] = Data['quality'].map(Avg)

In [31]:
Data.corr()

,fixed acidity,chlorides,total sulfur dioxide,density,sulphates,alcohol,quality,Avg_volatile_acidity,avg_Silphates
fixed acidity,1.000000,0.023086,0.091070,0.265331,-0.017143,-0.120881,-0.113663,0.095402,-0.099022
chlorides,0.023086,1.000000,0.198910,0.257211,0.016763,-0.360189,-0.209934,0.141714,-0.196038
total sulfur dioxide,0.091070,0.198910,1.000000,0.529881,0.134562,-0.448892,-0.174737,0.086355,-0.169254
density,0.265331,0.257211,0.529881,1.000000,0.074493,-0.780138,-0.307123,0.183376,-0.284258
sulphates,-0.017143,0.016763,0.134562,0.074493,1.000000,-0.017433,0.053678,-0.049643,0.066696
alcohol,-0.120881,-0.360189,-0.448892,-0.780138,-0.017433,1.000000,0.435575,-0.276908,0.390987
quality,-0.113663,-0.209934,-0.174737,-0.307123,0.053678,0.435575,1.000000,-0.732881,0.804818
Avg_volatile_acidity,0.095402,0.141714,0.086355,0.183376,-0.049643,-0.276908,-0.732881,1.000000,-0.744328
avg_Silphates,-0.099022,-0.196038,-0.169254,-0.284258,0.066696,0.390987,0.804818,-0.744328,1.000000

In [32]:
Data.drop("fixed acidity",axis=1,inplace=True)

In [33]:
Data.drop("sulphates",axis=1,inplace=True)

In [34]:
Data

,chlorides,total sulfur dioxide,density,alcohol,quality,Avg_volatile_acidity,avg_Silphates
0,0.045,170.0,1.00100,8.8,6,0.260564,0.491106
1,0.049,132.0,0.99400,9.5,6,0.260564,0.491106
2,0.050,97.0,0.99510,10.1,6,0.260564,0.491106
3,0.058,186.0,0.99560,9.9,6,0.260564,0.491106
4,0.058,186.0,0.99560,9.9,6,0.260564,0.491106
...,...,...,...,...,...,...,...
4893,0.039,92.0,0.99114,11.2,6,0.260564,0.491106
4894,0.047,168.0,0.99490,9.6,5,0.302011,0.482203
4895,0.041,111.0,0.99254,9.4,6,0.260564,0.491106
4896,0.022,110.0,0.98869,12.8,7,0.262767,0.503102
4897,0.020,98.0,0.98941,11.8,6,0.260564,0.491106

In [35]:
columns=["chlorides","total sulfur dioxide","alcohol",'density','Avg_volatile_acidity','avg_Silphates','quality']
Data = Data[columns]

In [38]:
Data.corr()

,chlorides,total sulfur dioxide,alcohol,density,Avg_volatile_acidity,avg_Silphates,quality
chlorides,1.000000,0.198910,-0.360189,0.257211,0.141714,-0.196038,-0.209934
total sulfur dioxide,0.198910,1.000000,-0.448892,0.529881,0.086355,-0.169254,-0.174737
alcohol,-0.360189,-0.448892,1.000000,-0.780138,-0.276908,0.390987,0.435575
density,0.257211,0.529881,-0.780138,1.000000,0.183376,-0.284258,-0.307123
Avg_volatile_acidity,0.141714,0.086355,-0.276908,0.183376,1.000000,-0.744328,-0.732881
avg_Silphates,-0.196038,-0.169254,0.390987,-0.284258,-0.744328,1.000000,0.804818
quality,-0.209934,-0.174737,0.435575,-0.307123,-0.732881,0.804818,1.000000

In [39]:
Data['quality'].value_counts()

quality
6    2198
5    1457
7     880
8     175
4     163
3      20
9       5
Name: count, dtype: int64

In [40]:
# Balancing the Data 
Concating_terms = []
n_samples = 2000
Unique_Class = Data['quality'].unique()

for Class in Unique_Class :

    Class_data = Data[Data['quality']==Class]
    Current_Count = len(Class_data)

    if Current_Count < n_samples :
        # Upsampling the data 
        resampled_Data = resample(
            Class_data,
            n_samples=n_samples,
            replace=True,
            random_state=50
        )

    elif Current_Count > n_samples :
        # DownSampling 
        resampled_Data = resample(
            Class_data,
            n_samples=n_samples,
            replace= False,
            random_state= 50
        )

    else :
        print("Not Every time Error Comes !")

    Concating_terms.append(resampled_Data)

Balanced_data = pd.concat(Concating_terms,ignore_index=True)

In [45]:
Balanced_data['quality'].value_counts()

quality
6    2000
5    2000
7    2000
8    2000
4    2000
3    2000
9    2000
Name: count, dtype: int64

In [46]:
Balanced_data

,chlorides,total sulfur dioxide,alcohol,density,Avg_volatile_acidity,avg_Silphates,quality
0,0.030,105.0,11.8,0.99407,0.260564,0.491106,6
1,0.064,152.0,9.3,0.99520,0.260564,0.491106,6
2,0.042,114.0,9.5,0.99784,0.260564,0.491106,6
3,0.076,124.0,10.1,0.99204,0.260564,0.491106,6
4,0.030,76.0,10.5,0.99202,0.260564,0.491106,6
...,...,...,...,...,...,...,...
13995,0.032,113.0,12.9,0.99030,0.298000,0.466000,9
13996,0.032,113.0,12.9,0.99030,0.298000,0.466000,9
13997,0.032,113.0,12.9,0.99030,0.298000,0.466000,9
13998,0.032,113.0,12.9,0.99030,0.298000,0.466000,9
13999,0.032,113.0,12.9,0.99030,0.298000,0.466000,9