In [8]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.utils import resample

In [5]:
Data = sns.load_dataset('tips')
Data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [6]:
Data.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [7]:
Data['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [10]:
# upsampling the Female Category 
Majority = Data[Data['sex'] == "Male"]
Minority = Data[Data['sex']== "Female"]

Upsampled_Minority = resample(
    Minority,
    n_samples=len(Majority),
    random_state=25,
    replace=True
)
Upsampled_Minority

     total_bill   tip     sex smoker   day    time  size
16        10.33  1.67  Female     No   Sun  Dinner     3
168       10.59  1.61  Female    Yes   Sat  Dinner     2
66        16.45  2.47  Female     No   Sat  Dinner     2
164       17.51  3.00  Female    Yes   Sun  Dinner     2
92         5.75  1.00  Female    Yes   Fri  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
198       13.00  2.00  Female    Yes  Thur   Lunch     2
121       13.42  1.68  Female     No  Thur   Lunch     2
158       13.39  2.61  Female     No   Sun  Dinner     2
37        16.93  3.07  Female     No   Sat  Dinner     3
155       29.85  5.14  Female     No   Sun  Dinner     5

[157 rows x 7 columns]

In [11]:
Final = pd.concat([Upsampled_Minority,Majority])

In [13]:
Final['smoker'].value_counts()

smoker
No     198
Yes    116
Name: count, dtype: int64

# Upsmapling the sex and Smoker As Group

In [33]:
Data['Smoker_Gender'] = Data['sex'].astype(str)+'_'+Data['smoker'].astype(str)

Data['Smoker_Gender'].value_counts()

Male_NO= Data[Data['Smoker_Gender'] == "Male_No"]
Male_Yes= Data[Data['Smoker_Gender'] == "Male_Yes"]
Female_No= Data[Data['Smoker_Gender'] == "Female_No"]
Female_Yes= Data[Data['Smoker_Gender'] == "Female_Yes"]

In [34]:
# Upsampling the Data 
Upsampled_Male_NO = resample(
    Male_NO,
    replace=True,
    n_samples=100,
    random_state=22
)
Upsampled_Male_Yes = resample(
    Male_Yes,
    replace=True,
    n_samples=100,
    random_state=22
)
Upsampled_Female_No = resample(
    Female_No,
    replace=True,
    n_samples=100,
    random_state=22
)
Upsampled_Female_Yes = resample(
    Female_Yes,
    replace=True,
    n_samples=100,
    random_state=22
)

In [35]:
List = [Upsampled_Female_No,Upsampled_Female_Yes,Upsampled_Male_NO,Upsampled_Male_Yes]


dfs = [df.reset_index(drop=True)  for df in List]
Final_Data = pd.concat(dfs,axis=0)

In [36]:
Final_Data['Smoker_Gender'].value_counts()

Smoker_Gender
Female_No     100
Female_Yes    100
Male_No       100
Male_Yes      100
Name: count, dtype: int64

In [30]:
Final_Data['sex'].value_counts()

sex
Male      200
Female    200
Name: count, dtype: int64

In [31]:
Final_Data['smoker'].value_counts()

smoker
Yes    200
No     200
Name: count, dtype: int64

In [39]:
Final_Data

    total_bill    tip     sex smoker   day    time  size Smoker_Gender
0        18.78   3.00  Female     No  Thur  Dinner     2     Female_No
1        10.33   1.67  Female     No   Sun  Dinner     3     Female_No
2         8.35   1.50  Female     No  Thur   Lunch     2     Female_No
3        16.99   1.01  Female     No   Sun  Dinner     2     Female_No
4        18.26   3.25  Female     No  Thur   Lunch     2     Female_No
..         ...    ...     ...    ...   ...     ...   ...           ...
95       25.21   4.29    Male    Yes   Sat  Dinner     2      Male_Yes
96       19.44   3.00    Male    Yes  Thur   Lunch     2      Male_Yes
97       32.90   3.11    Male    Yes   Sun  Dinner     2      Male_Yes
98       50.81  10.00    Male    Yes   Sat  Dinner     3      Male_Yes
99       20.53   4.00    Male    Yes  Thur   Lunch     4      Male_Yes

[400 rows x 8 columns]

In [ ]:
Final_Data.drop("Grouped",axis=1,inplace=True)
Final_Data.drop("smoker",axis=1,inplace=True)

In [42]:
Final_Data.drop("sex",axis=1,inplace=True)

In [46]:
Final_Data.to_csv("Cleaned_data.csv")

In [44]:
Final_Data['day'].value_counts()

day
Sat     135
Thur    119
Sun     100
Fri      46
Name: count, dtype: int64